name: Bug Report
description: Submit a bug report
title: "[Bug]: "
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: "ex. email@example.com"
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen? Include any context and what you were trying to accomplish.
      placeholder: Tell us what you expected to see!
      value: "It should work!"
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What is actually happening?
      placeholder: Tell us what you actually see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How does this bug occur?
      placeholder: Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant.
      value: "1. 2. 3."
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Possible Solution
      description: How do you think this can be resolved?
      placeholder: Please suggest a fix/reason for the bug, or any ideas you may have to implement the fix.
      value: "This might work..."
  - type: checkboxes
    id: guidelines
    attributes:
      label: Contributing Guidelines
      description: By submitting this issue, you agree that you have read and will follow our [Contributing Guidelines](/CONTRIBUTING.md)
      options:
        - label: "I agree to follow this project's Contributing Guidelines"
          required: true
