# Generated by Django 4.2.1 on 2023-06-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
