# Generated by Django 4.2.1 on 2023-06-06 05:02

from django.db import migrations
from django.core.management import call_command

def forward_func(apps, schema_editor):
    call_command('loaddata', '../fixtures/001_Locations.json', verbosity=2)
    print('Forward')

def reverse_func(apps, schema_editor):
    print('Reverse')

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_product_id_favorite_product_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
