# Generated by Django 4.2.1 on 2023-06-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_review_review_unique_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.location'),
        ),
    ]
