# Generated by Django 4.2.1 on 2023-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_product_store_product_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Bookmark',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_favorite',
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_bookmark'),
        ),
    ]
