# Generated by Django 4.2.1 on 2023-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_log_log_unique_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='liked_it',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
