# Generated by Django 4.2.1 on 2023-07-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_log_liked_it_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
